import { useState } from "react";
import "./Home.css";

import logoImg from "../assets/logo.png";

function Home() {
  const [textoFrase, setTextoFrase] = useState("");
  const [categoriaSelecionada, setCategoriaSelecionada] = useState(0);

  const allFrases = [
    {
      id: 1,
      nome: "motivação",
      frases: [
        "O esforço de hoje é o sucesso de amanhã.",
        "Acredite em si mesmo e vá além.",
        "Cada passo conta na jornada para o sucesso.",
        "O impossível é só uma questão de perspectiva.",
        "O que você faz hoje reflete no seu futuro.",
        "Desafios são oportunidades disfarçadas.",
        "Acredite no processo, e o resultado virá.",
        "O sucesso começa com a decisão de tentar.",
        "Não pare até se orgulhar.",
        "Grandes conquistas começam com pequenos passos.",
        "Você é mais forte do que imagina.",
        "O maior obstáculo está na sua mente.",
        "A única maneira de falhar é desistir.",
        "Quando você acredita em si, tudo se torna possível.",
        "Os maiores sonhos começam com um único passo.",
        "A perseverança vence todas as dificuldades.",
        "A única limitação que você tem é a que coloca em si mesmo.",
        "O sucesso não é final, o fracasso não é fatal; o que conta é a coragem de continuar.",
        "Cada dia é uma nova chance de fazer a diferença.",
        "O segredo do sucesso é a constância do propósito.",
      ],
    },
    {
      id: 2,
      nome: "bom dia",
      frases: [
        "Bom dia! Que seu dia seja repleto de alegria e boas energias.",
        "Acorde com gratidão e faça do seu dia o melhor possível.",
        "Bom dia! Que a felicidade te acompanhe durante todo o dia.",
        "Hoje é um novo dia para conquistar seus sonhos. Bom dia!",
        "Que o sol brilhe mais forte para iluminar sua jornada. Bom dia!",
        "Bom dia! Aproveite cada momento e faça ele valer a pena.",
        "Que seu dia seja leve, feliz e cheio de boas surpresas.",
        "Bom dia! O dia de hoje é uma nova oportunidade para ser feliz.",
        "Acorde com um sorriso e espalhe luz por onde passar. Bom dia!",
        "Bom dia! Que a paz e o amor estejam presentes no seu dia.",
        "O melhor de hoje começa com um simples bom dia. Que seja incrível!",
        "Bom dia! Que a sua manhã seja repleta de inspiração e energia positiva.",
        "Cada amanhecer é uma chance de recomeçar. Bom dia!",
        "Que seu dia seja cheio de sorrisos e boas vibrações. Bom dia!",
        "Bom dia! Que você tenha um dia produtivo e cheio de conquistas.",
        "A cada amanhecer, nasce uma nova esperança. Bom dia!",
        "Bom dia! Que a felicidade e a saúde te acompanhem em cada passo.",
        "Que o seu dia seja leve, feliz e cheio de boas notícias. Bom dia!",
        "Bom dia! Que você faça do seu dia um momento inesquecível.",
        "A vida é feita de bons dias e bons momentos. Que o seu seja maravilhoso!",
      ],
    },
    {
      id: 3,
      nome: "autoajuda",
      frases: [
        "A verdadeira mudança começa de dentro para fora.",
        "Não tenha medo de recomeçar. Cada dia é uma nova chance.",
        "Você é capaz de mais do que imagina, acredite nisso.",
        "O autoconhecimento é a chave para uma vida mais plena.",
        "A felicidade não é algo pronto, ela vem de suas ações.",
        "Cuidar de si é um ato de amor próprio.",
        "Não permita que o medo de errar te impeça de tentar.",
        "A melhor versão de você começa agora.",
        "A vida é feita de escolhas. Faça as que te fazem feliz.",
        "As dificuldades são oportunidades disfarçadas de desafios.",
        "Todo grande sonho começa com a coragem de tentar.",
        "Você não está sozinho na sua jornada, o apoio está ao seu redor.",
        "Desistir não é uma opção quando se acredita no seu potencial.",
        "Acredite no seu valor e tudo o que você conquistar será merecido.",
        "A verdadeira paz vem quando você se aceita do jeito que é.",
        "Não espere o momento perfeito, crie-o.",
        "Não se compare aos outros, sua jornada é única.",
        "O primeiro passo para mudar sua vida é mudar seus pensamentos.",
        "Às vezes, tudo o que você precisa é de uma pausa para se recompor.",
        "Sua vida, suas regras. Viva do seu jeito.",
      ],
    },
    {
      id: 4,
      nome: "gratidão",
      frases: [
        "A gratidão transforma o que temos em suficiente.",
        "Agradeça por cada pequeno momento, pois eles são os que mais contam.",
        "A gratidão é a memória do coração.",
        "Seja grato por tudo, até pelas lições que a vida te ensina.",
        "A gratidão traz paz ao coração e clareza à mente.",
        "Agradeça pelo que você tem, enquanto luta pelo que deseja.",
        "A gratidão é a chave que abre portas para abundância.",
        "O simples ato de agradecer muda nossa perspectiva de vida.",
        "A gratidão é um remédio para a alma.",
        "Cultive a gratidão e o universo te surpreenderá com mais motivos para agradecer.",
        "A cada amanhecer, agradeça por mais uma oportunidade de ser feliz.",
        "A gratidão ilumina até os dias mais escuros.",
        "Seja grato por todos os momentos, pois são eles que te moldam.",
        "A verdadeira abundância começa com a gratidão.",
        "Gratidão transforma a dor em aprendizado e a perda em sabedoria.",
        "A gratidão é o caminho para a felicidade verdadeira.",
        "Quanto mais grato você for, mais razões encontrará para ser grato.",
        "Pratique a gratidão todos os dias e verá sua vida se transformar.",
        "A gratidão é uma atitude, não uma reação a circunstâncias.",
        "A vida é mais colorida quando olhamos por ela com olhos de gratidão.",
      ],
    },
    {
      id: 5,
      nome: "fé",
      frases: [
        "A fé move montanhas e transforma vidas.",
        "Quando a fé é forte, nada pode te derrubar.",
        "Com fé, tudo é possível. Não perca a esperança.",
        "A fé é a luz que ilumina o caminho da dúvida.",
        "Mesmo nos momentos difíceis, mantenha sua fé inabalável.",
        "Acredite, confie e aguarde, pois tudo tem o seu tempo.",
        "A fé não é a certeza de que tudo vai dar certo, mas a confiança de que tudo tem um propósito.",
        "Quando a fé é verdadeira, ela nos dá forças para continuar.",
        "A fé é a ponte entre o agora e o que ainda está por vir.",
        "Com fé, a jornada fica mais leve, pois sabemos que não estamos sozinhos.",
        "A fé não conhece limites, ela é a força que nos impulsiona.",
        "Nos momentos de dúvida, a fé é o que nos mantém firmes.",
        "A fé é o combustível da esperança.",
        "O segredo é ter fé no impossível e coragem para agir.",
        "Onde a fé entra, o impossível começa a se tornar possível.",
        "Com fé, o futuro é sempre promissor.",
        "A fé nos faz enxergar além das dificuldades e confiar no plano maior.",
        "A fé é o que nos mantém de pé quando tudo ao nosso redor está desmoronando.",
        "Não importa o tamanho da tempestade, com fé, sempre haverá sol depois da chuva.",
        "A fé é o alicerce de uma vida plena e cheia de sentido.",
      ],
    },
    {
      id: 6,
      nome: "coragem",
      frases: [
        "Coragem não é a ausência de medo, mas a decisão de que algo é mais importante que o medo.",
        "A verdadeira coragem é seguir em frente, mesmo quando o caminho é desconhecido.",
        "A coragem nasce quando você decide dar o primeiro passo, mesmo sem ver o fim.",
        "Acredite em sua coragem e verá que é capaz de enfrentar qualquer desafio.",
        "Coragem não é não ter medo, é agir apesar dele.",
        "A coragem é a chave para transformar os seus sonhos em realidade.",
        "O maior ato de coragem é ser fiel a si mesmo.",
        "Coragem é sair da zona de conforto e dar o primeiro passo rumo ao desconhecido.",
        "Toda grande conquista começa com a coragem de tentar.",
        "A coragem não vem de não sentir medo, mas de agir apesar dele.",
        "Não espere pela coragem para agir, comece com a ação e a coragem virá.",
        "A coragem é a luz que ilumina os caminhos da incerteza.",
        "Você é mais corajoso do que imagina, basta acreditar.",
        "A coragem é enfrentar a adversidade com a cabeça erguida e o coração firme.",
        "Às vezes, é necessário dar o salto de fé, mesmo sem ver a rede de segurança.",
        "Coragem é dar o primeiro passo, mesmo quando você não vê toda a escada.",
        "Não há nada mais forte que a coragem de ser quem você realmente é.",
        "Cada passo corajoso que você dá, abre caminho para novas possibilidades.",
        "A coragem é a força interior que nos faz seguir em frente, apesar de tudo.",
        "Com coragem, você pode transformar qualquer obstáculo em uma oportunidade.",
      ],
    },
    {
      id: 7,
      nome: "amor",
      frases: [
        "O amor é a força mais poderosa do universo.",
        "Amar é entender que, apesar das diferenças, somos todos um.",
        "Onde há amor, há vida.",
        "O amor não se encontra, ele se constrói.",
        "Amar é dar sem esperar nada em troca.",
        "O amor é paciente, é bondoso, é eterno.",
        "Amar é ser vulnerável e, ainda assim, se entregar.",
        "O amor é a linguagem universal que todos compreendem.",
        "A verdadeira beleza do amor é que ele não exige perfeição.",
        "O amor é o maior presente que podemos dar e receber.",
        "Quando o amor é verdadeiro, ele nunca se esgota.",
        "O amor transforma, cura e fortalece.",
        "Amar é escolher estar ao lado de alguém, não por obrigação, mas por desejo.",
        "No fim das contas, o que realmente importa é o amor que damos e recebemos.",
        "O amor nos ensina a ser melhores e a ver o mundo com olhos mais suaves.",
        "Amar é compartilhar alegrias e enfrentar juntos as adversidades.",
        "O amor verdadeiro é aquele que nos liberta e nos faz crescer.",
        "Ame sem medo, ame sem limites.",
        "O amor é o melhor remédio para todos os males.",
        "No amor, o coração encontra sua verdadeira casa.",
      ],
    },
    {
      id: 8,
      nome: "paz",
      frases: [
        "A paz começa com um sorriso.",
        "Onde há paz, há harmonia.",
        "A paz não é apenas a ausência de conflito, mas a presença de compreensão.",
        "O maior presente que você pode oferecer a si mesmo é a paz de espírito.",
        "A paz é a verdadeira riqueza.",
        "A paz é encontrada dentro de nós, quando nos libertamos da inquietação.",
        "A paz é o caminho, não o destino.",
        "A paz começa com a aceitação do que não podemos mudar.",
        "A verdadeira paz vem quando encontramos equilíbrio entre o corpo, a mente e o espírito.",
        "A paz interior é o maior poder que você pode possuir.",
        "A paz é o resultado de cultivar a tranquilidade dentro de si.",
        "A paz não é um luxo, é uma necessidade para uma vida plena.",
        "A paz não se conquista com palavras, mas com atitudes.",
        "Quando você encontra a paz dentro de si, o mundo ao seu redor também encontra a paz.",
        "Cultive a paz, e ela se espalhará como um raio de luz.",
        "A paz é a verdadeira liberdade.",
        "A paz é o antídoto para todas as tensões e ansiedades.",
        "O silêncio traz a paz que o barulho nunca pode oferecer.",
        "Onde há paz, tudo se torna possível.",
        "A paz de espírito é a maior conquista da vida.",
      ],
    },
    {
      id: 9,
      nome: "superação",
      frases: [
        "A superação começa no momento em que você decide não desistir.",
        "Cada obstáculo é uma oportunidade disfarçada de desafio.",
        "A verdadeira superação é crescer com as dificuldades que enfrentamos.",
        "Superar não significa esquecer, mas aprender a lidar com o que nos machuca.",
        "A força para superar vem de dentro de você, nunca duvide disso.",
        "A superação é o reflexo da nossa capacidade de adaptação e resiliência.",
        "Quem supera sabe que o impossível só existe até que alguém se atreva a conquistá-lo.",
        "Você é mais forte do que imagina, e a superação te mostrará isso.",
        "A superação é uma jornada, não um destino.",
        "Cada passo que damos na direção da superação nos torna mais sábios e mais fortes.",
        "Acredite em si mesmo, pois você é capaz de superar qualquer desafio.",
        "A superação é um exercício diário de coragem e persistência.",
        "A maior superação é a que acontece dentro de nós.",
        "Não importa o tamanho do desafio, sempre há uma maneira de superá-lo.",
        "A superação é a chave para transformar dificuldades em aprendizado.",
        "Superar é o que nos torna mais fortes para enfrentar o que vem pela frente.",
        "O maior desafio da vida é superar os nossos próprios limites.",
        "Com cada superação, crescemos em sabedoria e força.",
        "Você pode tudo quando decide que não vai desistir.",
        "A superação é a prova de que você é capaz de vencer qualquer adversidade.",
      ],
    },
    {
      id: 10,
      nome: "esperança",
      frases: [
        "A esperança é o combustível que mantém nossos sonhos vivos.",
        "Quando você tem esperança, o impossível se torna apenas uma palavra.",
        "A esperança é a chama que nos mantém em movimento, mesmo nos momentos difíceis.",
        "Nunca perca a esperança, pois ela é a última a morrer.",
        "A esperança é a certeza de que, mesmo em meio à tempestade, o sol irá brilhar novamente.",
        "A esperança é o que nos dá forças para continuar a caminhada.",
        "Onde há esperança, há sempre uma chance de recomeço.",
        "A esperança é uma luz que nunca se apaga.",
        "A esperança é o farol que nos guia nas noites mais escuras.",
        "Com esperança, a jornada se torna mais leve e o futuro mais brilhante.",
        "A esperança não é esperar, é agir com fé no que está por vir.",
        "A esperança é a irmã da fé, sempre nos conduzindo para frente.",
        "Nunca deixe de ter esperança, pois ela é o primeiro passo para a mudança.",
        "Com esperança, não há problema que seja grande demais para resolver.",
        "A esperança é o elo que une os sonhos ao futuro.",
        "A esperança não se define pelo que vemos, mas pelo que acreditamos.",
        "Onde há esperança, há sempre uma possibilidade de um amanhã melhor.",
        "A esperança é o que nos mantém firmes, mesmo quando tudo parece perdido.",
        "Com esperança, tudo se torna possível.",
      ],
    },
    {
      id: 11,
      nome: "persistência",
      frases: [
        "A persistência é o caminho para alcançar grandes conquistas.",
        "Não desista, mesmo quando tudo parecer difícil.",
        "A chave para o sucesso é a persistência diante das adversidades.",
        "Grandes feitos são construídos com pequenas doses de persistência.",
        "A persistência é o que separa os vencedores dos que desistem no meio do caminho.",
        "O segredo da superação é a persistência, mesmo nos momentos de fracasso.",
        "Com persistência, não há obstáculos grandes o suficiente para nos parar.",
        "Persistir é acreditar que, apesar das dificuldades, o sucesso está ao alcance.",
        "A persistência é uma forma silenciosa de fazer a diferença.",
        "O sucesso não é sobre nunca cair, mas sobre sempre se levantar e persistir.",
        "A persistência é o melhor remédio para aqueles que duvidam do seu potencial.",
        "Seja persistente, pois o sucesso pode estar mais perto do que você imagina.",
        "A verdadeira vitória vem para aqueles que nunca desistem.",
        "Cada erro é uma lição que torna a persistência ainda mais poderosa.",
        "Com persistência, você pode transformar dificuldades em oportunidades.",
        "O segredo do sucesso é não parar, mesmo quando tudo parece impossível.",
        "Não importa quantas vezes você caia, o importante é persistir e seguir em frente.",
        "Persistir é ter fé no processo, mesmo quando os resultados não são imediatos.",
        "A persistência é o combustível dos grandes vencedores.",
      ],
    },
    {
      id: 12,
      nome: "determinação",
      frases: [
        "A determinação é o que transforma sonhos em realidade.",
        "Com determinação, você pode superar qualquer obstáculo que apareça.",
        "A força de vontade é o que separa os que conseguem dos que desistem.",
        "A determinação é o segredo para alcançar objetivos que parecem impossíveis.",
        "Acredite em sua determinação e verá o impossível se tornar possível.",
        "Nada pode parar alguém determinado a alcançar seu objetivo.",
        "A determinação é o alicerce de uma vida de sucesso.",
        "Não basta querer, é preciso ter a determinação de agir.",
        "Com determinação, você vai além dos seus próprios limites.",
        "A verdadeira determinação está em continuar, mesmo quando tudo ao seu redor pede para parar.",
        "A determinação é o que nos faz levantar a cada queda.",
        "Acredite no poder da sua determinação e em seu potencial ilimitado.",
        "A determinação transforma desafios em marcos de superação.",
        "Quando a determinação é maior que o medo, você consegue conquistar tudo.",
        "Determinação é ter a coragem de seguir em frente, mesmo sem ter todas as respostas.",
        "Com determinação, não há nada que possa te impedir de alcançar seu sonho.",
        "A determinação é uma força imbatível quando combinada com a paixão.",
        "Acredite no seu poder de determinação e faça acontecer.",
        "Sem determinação, até os maiores sonhos se tornam apenas possibilidades.",
      ],
    },
    {
      id: 13,
      nome: "resiliência",
      frases: [
        "A resiliência é a capacidade de transformar dor em aprendizado.",
        "A resiliência não está em evitar quedas, mas em se levantar mais forte.",
        "Ser resiliente é aprender a prosperar, mesmo em tempos difíceis.",
        "A resiliência nos permite seguir em frente, mesmo quando tudo parece desmoronar.",
        "Com resiliência, encontramos forças onde não imaginávamos que existiam.",
        "A resiliência é a arte de fazer da adversidade um trampolim para o sucesso.",
        "Quanto mais desafiadora a jornada, mais profunda se torna nossa resiliência.",
        "A verdadeira força está em ser resiliente diante das dificuldades da vida.",
        "A resiliência é o que nos permite ir além dos nossos limites.",
        "A vida vai te testar, mas a resiliência é o que te ajuda a passar por tudo.",
        "A resiliência é a chave para transformar dificuldades em oportunidades.",
        "Com resiliência, somos capazes de nos adaptar e continuar, mesmo diante das tempestades.",
        "A resiliência nos ensina que, após a dor, vem o crescimento.",
        "A resiliência é a capacidade de manter a esperança, mesmo nos momentos de adversidade.",
        "Ser resiliente é saber que, após o inverno, vem a primavera.",
        "A resiliência é o poder de recomeçar a cada queda.",
        "A vida é cheia de altos e baixos, mas a resiliência é o que nos mantém firmes.",
        "A verdadeira resiliência é aprender a sorrir, mesmo nos momentos de dor.",
        "Com resiliência, até os maiores desafios se tornam superáveis.",
      ],
    },
    {
      id: 14,
      nome: "sabedoria",
      frases: [
        "A sabedoria é o conhecimento aliado à experiência.",
        "A sabedoria não é aprender tudo, mas entender o essencial.",
        "A sabedoria é saber ouvir mais e falar menos.",
        "A sabedoria é a capacidade de ver além do óbvio.",
        "Com sabedoria, sabemos que o conhecimento é infinito e sempre há algo novo a aprender.",
        "A sabedoria é a luz que guia nossas decisões em tempos de incerteza.",
        "A sabedoria é a paz que vem com a aceitação do que não podemos mudar.",
        "A verdadeira sabedoria está em saber que nunca sabemos tudo.",
        "Sabedoria é entender que cada erro é uma lição valiosa.",
        "A sabedoria é o dom de aprender com o passado e viver plenamente o presente.",
        "A sabedoria nos ensina a fazer as perguntas certas, não apenas as respostas.",
        "O caminho para a sabedoria é percorrido com paciência e reflexão.",
        "A sabedoria não está no quanto você sabe, mas no quanto você sabe compartilhar com os outros.",
        "A sabedoria nos guia a tomar decisões que são boas para o nosso futuro.",
        "Quem possui sabedoria sabe que a vida é feita de escolhas e aprendizados.",
        "A sabedoria é o reconhecimento da verdade, mesmo quando ela é difícil de encarar.",
        "A verdadeira sabedoria é a capacidade de manter a mente aberta e receptiva.",
        "A sabedoria nos ensina a usar nossos erros como trampolins para o sucesso.",
        "Sabedoria é não apenas aprender com as próprias experiências, mas também com as dos outros.",
      ],
    },
    {
      id: 15,
      nome: "foco",
      frases: [
        "O foco é o que te leva do ponto A ao ponto B, sem distrações.",
        "Onde há foco, o sucesso não demora a chegar.",
        "Foco é escolher uma direção e não olhar para os lados.",
        "Com foco, qualquer meta se torna alcançável.",
        "Foco é a capacidade de dizer não às distrações.",
        "Quando você tem foco, o impossível se torna apenas um obstáculo a ser superado.",
        "Foco é a força que transforma sonhos em realizações.",
        "Com foco, você encontra as soluções para os seus problemas.",
        "O segredo do sucesso é manter o foco no objetivo final.",
        "Sem foco, até os melhores planos podem se perder.",
        "A chave para o sucesso está em manter o foco nas suas prioridades.",
        "Com foco, cada passo se torna um avanço em direção ao seu objetivo.",
        "Foco é o que transforma pequenos esforços em grandes resultados.",
        "A disciplina vem do foco, e com disciplina vem o sucesso.",
        "Foco é a capacidade de manter os olhos no prêmio, mesmo nas dificuldades.",
        "Com foco, você se aproxima a cada dia da sua realização.",
        "A verdadeira força vem do foco naquilo que é mais importante.",
        "Foco não é sobre trabalhar mais, mas trabalhar melhor.",
        "O foco é o motor que impulsiona você na direção dos seus sonhos.",
      ],
    },
    {
      id: 16,
      nome: "liberdade",
      frases: [
        "A liberdade é a verdadeira essência do ser humano.",
        "Ser livre é viver sem as correntes do medo ou da dúvida.",
        "A liberdade é a oportunidade de ser quem você realmente é.",
        "A liberdade não se encontra fora de você, ela mora dentro.",
        "Liberdade é saber que, ao fazer suas escolhas, você é dono do seu destino.",
        "A liberdade é o maior dos bens que podemos conquistar.",
        "Ser livre é fazer o que ama, sem restrições ou amarras.",
        "A liberdade não significa fazer tudo o que quer, mas ser capaz de viver com autenticidade.",
        "A verdadeira liberdade é a liberdade de ser você mesmo.",
        "Com liberdade vem a responsabilidade de seguir o próprio caminho.",
        "A liberdade de pensamento é o primeiro passo para a liberdade de ação.",
        "Liberdade é viver sem medo de ser quem você é.",
        "A liberdade é o que nos permite seguir nossos próprios sonhos e metas.",
        "A maior prisão é a mente; a maior liberdade é o pensamento livre.",
        "Liberdade é a capacidade de fazer as suas próprias escolhas.",
        "A liberdade não é algo que se conquista de fora para dentro, mas de dentro para fora.",
        "Ser livre é ser capaz de dizer sim para seus sonhos e não para o medo.",
        "A verdadeira liberdade vem quando você deixa de se importar com o julgamento alheio.",
        "Liberdade é poder viver de acordo com seus próprios valores e princípios.",
      ],
    },
    {
      id: 17,
      nome: "criatividade",
      frases: [
        "A criatividade é a inteligência se divertindo.",
        "A verdadeira criatividade é pensar fora da caixa.",
        "Ser criativo é ver oportunidades onde outros veem obstáculos.",
        "A criatividade não tem limites, ela é alimentada pela imaginação.",
        "A criatividade é o poder de transformar ideias em realidades.",
        "A criatividade começa quando você ousa pensar diferente.",
        "Tudo o que você precisa para ser criativo é a coragem de tentar.",
        "A criatividade é a chave para resolver os problemas de uma maneira única.",
        "Ser criativo é ter a liberdade de explorar novas possibilidades.",
        "A criatividade nasce da combinação de ideias diferentes.",
        "A criatividade é o que torna a vida mais interessante e cheia de possibilidades.",
        "Cada momento é uma oportunidade para ser criativo.",
        "Com criatividade, podemos mudar o mundo de formas que nunca imaginamos.",
        "A criatividade é a arte de transformar o impossível em possível.",
        "Toda inovação começa com uma ideia criativa.",
        "Ser criativo é olhar para o ordinário e ver o extraordinário.",
        "A criatividade é um jogo constante entre o conhecimento e a imaginação.",
        "A criatividade é o motor das grandes mudanças no mundo.",
        "Na criatividade, não há limites, apenas infinitas possibilidades.",
      ],
    },
    {
      id: 18,
      nome: "equilíbrio",
      frases: [
        "O equilíbrio é a base de uma vida saudável e harmoniosa.",
        "Encontrar equilíbrio é saber dar a devida atenção a todas as áreas da vida.",
        "O segredo do equilíbrio está em saber quando avançar e quando descansar.",
        "Equilíbrio não é algo que encontramos, mas algo que construímos diariamente.",
        "A verdadeira paz vem quando conseguimos equilibrar mente, corpo e espírito.",
        "Equilíbrio é fazer escolhas que sustentem o bem-estar a longo prazo.",
        "O equilíbrio é a chave para lidar com os altos e baixos da vida.",
        "Quando há equilíbrio, há tranquilidade e clareza para tomar as melhores decisões.",
        "O equilíbrio é a arte de manter a paz mesmo nas tempestades da vida.",
        "Equilibrar nossas emoções nos ajuda a tomar decisões mais racionais e conscientes.",
        "O equilíbrio está na harmonia entre o trabalho, o descanso e o lazer.",
        "A vida é mais leve quando encontramos o equilíbrio entre o que somos e o que queremos ser.",
        "Equilíbrio é fazer uma pausa para refletir e retornar mais forte.",
        "Encontrar equilíbrio é saber que cada parte da vida tem seu tempo e lugar.",
        "A verdadeira felicidade vem do equilíbrio entre as emoções e a razão.",
        "Equilíbrio é saber a hora certa de agir e a hora certa de esperar.",
        "Com equilíbrio, somos mais capazes de lidar com os desafios da vida.",
        "O equilíbrio nos ensina que cada coisa tem seu tempo e espaço.",
        "O equilíbrio é o segredo para uma vida de bem-estar e serenidade.",
      ],
    },
    {
      id: 21,
      nome: "desculpas",
      frases: [
        "Desculpe pelo que eu disse quando estava com fome. Eu prometo que não sou assim normalmente.",
        "Eu não queria te magoar, só que às vezes minha boca fala mais rápido que meu cérebro.",
        "Desculpe se te fiz sentir mal, não era minha intenção, mas confesso que meu filtro não estava funcionando.",
        "Eu sei que errei, mas me dá uma chance de melhorar! Prometo que a próxima será melhor.",
        "Desculpa pela minha falta de noção, às vezes meu cérebro entra no modo automático.",
        "Eu te devo desculpas... e talvez um presente para tentar compensar!",
        "Se eu soubesse que minha palavra ia te machucar, teria guardado na caixa de pensamentos!",
        "Desculpe por não ter agido como deveria. Às vezes, a pressão me faz dar passos em falso.",
        "Eu juro que vou melhorar, mas só se você me der mais uma chance de tentar.",
        "Me desculpe, minha ideia de piada nem sempre é a mais adequada. Vou tentar melhorar.",
        "Eu sei que errei e vou tentar aprender com isso. Desculpe por te deixar frustrado.",
        "Desculpe por não ser perfeito. Mas quem é, né? Só me deixe corrigir os meus erros.",
        "Eu sou bom em fazer trapalhadas, mas também sou bom em pedir desculpas!",
        "Desculpe se fui rude. Às vezes, falo antes de pensar, mas não era minha intenção.",
        "Eu realmente sinto muito, minha boca foi mais rápida que meu cérebro. Vou tentar pensar mais antes de falar!",
        "Desculpe, mas você sabe como é... todo mundo tem aquele dia em que tudo dá errado.",
        "Desculpe se te decepcionei. Quero mostrar que posso ser melhor da próxima vez.",
      ],
    },
    {
      id: 22,
      nome: "inspiração",
      frases: [
        "Acredite em seus sonhos e tudo será possível.",
        "O único limite para o seu sucesso é a sua determinação.",
        "Não importa o quão devagar você vá, desde que não pare.",
        "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
        "O impossível é apenas uma opinião, não um fato.",
        "O maior erro que você pode cometer é ter medo de cometer erros.",
        "O futuro pertence àqueles que acreditam na beleza dos seus sonhos.",
        "Se você quer alcançar a grandeza, pare de pedir permissão.",
        "O sucesso não é o fim, o fracasso não é fatal: o que importa é a coragem de continuar.",
        "Nunca é tarde para ser o que você poderia ter sido.",
      ],
    },
    {
      id: 23,
      nome: "amigos",
      frases: [
        "Amigos são a família que escolhemos para nós mesmos.",
        "A amizade verdadeira é aquela que não se desfaz com o tempo.",
        "Com amigos ao lado, qualquer desafio se torna mais fácil.",
        "Amigos são como estrelas. Nem sempre podemos vê-los, mas sabemos que estão lá.",
        "A vida é melhor com amigos que te fazem rir até a barriga doer.",
        "Amigos são aqueles que sabem de tudo sobre você e ainda assim te amam.",
        "A amizade não é sobre quem você conhece há mais tempo, mas sobre quem chegou e nunca foi embora.",
        "Amigos não são aqueles que sempre concordam com você, mas sim os que te fazem crescer.",
        "A amizade verdadeira não tem fim, ela apenas se fortalece com o tempo.",
        "Amigos são os pilares que nos ajudam a suportar os dias mais difíceis.",
      ],
    },
    {
      id: 26,
      nome: " mistério",
      frases: [
        "O universo é vasto e cheio de segredos esperando para serem descobertos.",
        "Às vezes, o maior mistério é a própria existência.",
        "O infinito é apenas uma palavra que tentamos entender com nossa mente limitada.",
        "O mistério da vida é o que nos mantém curiosos, explorando o desconhecido.",
        "Cada estrela no céu é um enigma, e cada planeta, uma história não contada.",
        "Talvez sejamos apenas um sonho de alguma civilização distante.",
        "O que chamamos de 'normal' é apenas um reflexo da nossa falta de compreensão do que é possível.",
        "O universo não se importa com o que achamos que sabemos, ele é imenso e indiferente.",
        "O mistério de onde viemos e para onde vamos é o maior enigma da humanidade.",
        "A verdade é que, em um universo tão grande, estamos todos conectados de maneiras que nem imaginamos.",
        "O tempo é uma ilusão, e o espaço é o grande palco onde nossa história se desenrola.",
        "Talvez as respostas que procuramos não existam. Talvez o mistério seja a resposta.",
        "Às vezes, a maior descoberta que fazemos é perceber o quão pequenos somos diante do universo.",
        "Quando olhamos para as estrelas, estamos olhando para o passado, mas também para o futuro.",
        "A vida é o maior mistério que jamais poderemos resolver, e talvez seja isso que a torna tão fascinante.",
        "Existem mais perguntas do que respostas, mas é isso que torna o mistério tão emocionante.",
        "O cosmos está repleto de enigmas, e talvez a maior missão da humanidade seja se perguntar: 'E se?'",
        "O infinito pode parecer distante, mas ele está em cada momento que vivemos e cada escolha que fazemos.",
        "O maior mistério não é o que está além das estrelas, mas o que está dentro de nós mesmos.",
        "Tudo o que sabemos é uma gota; o que ignoramos é um oceano.",
      ],
    },
  ];

  function handleCategoria(index: number) {
    setCategoriaSelecionada(index);
  }

function gerarFrase(){
let numeroAleatorio = Math.floor(Math.random() * allFrases[categoriaSelecionada].frases.length)
setTextoFrase(`"${allFrases[categoriaSelecionada].frases[numeroAleatorio]}"`)
}

  return (
    <div className="container">
      <img className="logo" src={logoImg} alt="logo frases" />

      <h2 className="title"> Categorias</h2>
      <section className="category-area">
        {allFrases.map((item, index) => (
          <button
            key={item.id}
            className="category-button"
            style={{
              borderWidth:
                item.nome === allFrases[categoriaSelecionada].nome ? 2 : 0,
              borderColor: "#1fa4db",
            }}
            onClick={() => handleCategoria(index)}
          >
            {item.nome}
          </button>
        ))}
      </section>

      <button className="button-frase" onClick={gerarFrase}>Gerar frases</button>

      {textoFrase !== "" && <p className="textoFrase">{textoFrase}</p>}
    </div>
  );
}

export default Home;
